
# Ultralytics Multi-GPU training temp file (should be automatically deleted after use)
overrides = {'task_name': 'detect', 'mode': 'train', 'model_str': 'ultralytics/cfg_yaml/model_yaml/v8/yolov8.yaml', 'data_str': 'datasets/coco128/coco128.yaml', 'epochs': 1, 'time': None, 'patience': 100, 'batch': 2, 'imgsz': 640, 'save': True, 'save_period': -1, 'cache': False, 'device': [7], 'workers': 8, 'project': None, 'name': 'train13', 'exist_ok': False, 'pretrained': True, 'optimizer': 'auto', 'verbose': True, 'seed': 0, 'deterministic': True, 'single_cls': False, 'rect': False, 'cos_lr': False, 'close_mosaic': 10, 'resume': False, 'amp': True, 'fraction': 1.0, 'profile': False, 'freeze': None, 'multi_scale': False, 'overlap_mask': True, 'mask_ratio': 4, 'dropout': 0.0, 'val': True, 'split': 'val', 'save_json': False, 'save_hybrid': False, 'conf': None, 'iou': 0.7, 'max_det': 300, 'half': False, 'dnn': False, 'plots': True, 'source': None, 'vid_stride': 1, 'stream_buffer': False, 'visualize': False, 'augment': False, 'agnostic_nms': False, 'classes': None, 'retina_masks': False, 'embed': None, 'show': False, 'save_frames': False, 'save_txt': False, 'save_conf': False, 'save_crop': False, 'show_labels': True, 'show_conf': True, 'show_boxes': True, 'line_width': None, 'format': 'torchscript', 'keras': False, 'optimize': False, 'int8': False, 'dynamic': False, 'simplify': False, 'opset': None, 'workspace': 4, 'nms': False, 'lr0': 0.01, 'lrf': 0.01, 'momentum': 0.937, 'weight_decay': 0.0005, 'warmup_epochs': 3.0, 'warmup_momentum': 0.8, 'warmup_bias_lr': 0.1, 'box': 7.5, 'cls': 0.5, 'dfl': 1.5, 'pose': 12.0, 'kobj': 1.0, 'label_smoothing': 0.0, 'nbs': 64, 'hsv_h': 0.015, 'hsv_s': 0.7, 'hsv_v': 0.4, 'degrees': 0.0, 'translate': 0.1, 'scale': 0.5, 'shear': 0.0, 'perspective': 0.0, 'flipud': 0.0, 'fliplr': 0.5, 'mosaic': 1.0, 'mixup': 0.0, 'copy_paste': 0.0, 'auto_augment': 'randaugment', 'erasing': 0.4, 'crop_fraction': 1.0, 'cfg': None, 'tracker': 'botsort.yaml', 'ch': 1, 'save_dir': '/home/gcsx/ANG/ultralytics-24-03-26/runs/detect/train13'}

if __name__ == "__main__":
    from ultralytics.projects.yolo.detect.detection_trainer import Detection_Trainer
    from ultralytics.utils import DEFAULT_PARAM_DICT

    default_param = DEFAULT_PARAM_DICT.copy()
    default_param.update(save_dir='')   # handle the extra key 'save_dir'
    trainer = Detection_Trainer(default_param=default_param, overrides=overrides)
    results = trainer.DDP_or_normally_train()
